### ISSUE TITLE
alpine:3.10 (py3.7) is incompatible with comunity/testing branch

### ISSUE THREAD

**Issue by Suika** [czeni/opencv-video-minimal#2]
```
~ # python3
Error relocating /usr/lib/libpython3.8.so.1.0: copy_file_range: symbol not found
```

Python 3.8 only exists in edge and does not exist in Alpine 3.10.

My guess is that you are using `alpine:3.10` which is using py3.7 but you are also pulling `py-numpy py-numpy-dev` from community branch which are built against py3.8, which in turn could/would cause problems in the whole setup.

**Comment by czeni** [comment]
I have already working on this issues for several days and managed to solve them in the latest version.
```
/ # python3
Python 3.8.0 (default, Nov  5 2019, 16:43:42) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy, cv2
>>> numpy.__version__
'1.17.4'
>>> cv2.__version__
> '4.1.2'
> >>> 
```

**Comment by Odianosen25** [comment]
@czeni,

I just tried building using the latest, and I am having the same issue as the topic here.

Please anyway I can get around this?

Regards

**Comment by czeni** [comment]
Somethng was wrong with the current python3 and musl versions.
I managed to solve the problem and introduced int the latest docker file.

If you want to use the latest be sure to remove all cached image and repull the latest one.
If you want to build a new image than you must got the linking broken somehow that I cannot solve.
