### ISSUE TITLE
Python 3.7.5

### ISSUE THREAD

**Issue by Odianosen25** [czeni/opencv-video-minimal#3]
Hello @czeni,

Thanks for this and it builds fine. But please is it possible for me to build based on python 3.7.5 instead of 3.8?

Thanks

**Comment by czeni** [comment]
The image uses the latest version from the alpine repos.
Python 3.8 should be compatible with 3.7 and all application that run on py3.7 should run on py3.8.

**Comment by Odianosen25** [comment]
Hello @czeni,

Thanks for the response. But it is not all modules that are 3.8 compatible. Like for example, our code uses aiohttp for critical stuffs, and we haven't upgraded to the latest yet; so based on this, aiohttp is not compatible in our system with 3.8, as we don't use the latest.

Based on this, we still have to make use of 3.7 for the mean time, and the reason for my asking please.

Kind regards

**Comment by czeni** [comment]
I have pinpointed a older Apline Linux version for Python3.7 from the main repo in a separate tag.
```
$ docker run --rm -ti czentye/opencv-video-minimal:4.2-py3.7.5
/ # python
Python 3.7.5 (default, Oct 17 2019, 12:25:15)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'4.2.0'
>>>
```
Regards

**Comment by Odianosen25** [comment]
Oh thank you boss, that is very kind of you. Will give it a short.

Kind regards

**Comment by Odianosen25** [comment]
Hello @czeni,

Thanks for this again, but I am having this issue

```
ImportError: Error relocating /usr/lib/python3.7/site-packages/cv2/python-3.7/cv2.cpython-37m-x86_64-linux-gnu.so: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
```
ANy ideas pls?

**Comment by Odianosen25** [comment]
The interesting thing is that that file exists

```
bash-5.0# cd /usr/lib/python3.7/site-packages/cv2/
bash-5.0# ls
__init__.py         __pycache__         config-3.7.py       config.py           load_config_py2.py  load_config_py3.py  python-3.7
bash-5.0# cd python-3.7
bash-5.0# ls
cv2.cpython-37m-x86_64-linux-gnu.so
```
But not sure why the error

**Comment by czeni** [comment]
Stange issue. I have just pulled the image from docker hub and I could import cv2 without error.
```
$ docker pull czentye/opencv-video-minimal:4.2-py3.7.5
4.2-py3.7.5: Pulling from czentye/opencv-video-minimal
89d9c30c1d48: Already exists
f5b7e9eb54ed: Pull complete
Digest: sha256:5f666e1188ec19a405d6104fcbc874eaf53633baa7ae182e367972694e007c67
Status: Downloaded newer image for czentye/opencv-video-minimal:4.2-py3.7.5
docker.io/czentye/opencv-video-minimal:4.2-py3.7.5
$ docker run --rm -ti czentye/opencv-video-minimal:4.2-py3.7.5
/ #
/ #
/ #
/ # python3
Python 3.7.5 (default, Oct 17 2019, 12:25:15)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.sqr
cv2.sqrBoxFilter(  cv2.sqrt(
>>> cv2.sqrt(25)
array([[5.],
       [0.],
       [0.],
       [0.]])
>>>
```
Maybe you can try another previous image with cv2 version.

**Comment by Odianosen25** [comment]
Hello @czeni,

Yes I also used the same image in Azure CI, and it works fine in Azure; though had to install a couple of packages first anyway. 

I am presently having this issue in my local instance, on an Ubuntu server on an i7 PC, and this pops up. Though will keep looking, hopefully I will figure it out soon.

Kind regards
